#!/usr/bin/env python3
"""
One-off (re-runnable) backfill of NEPSE daily index history.

  python scripts/backfill_history.py                 # fill data/history/index.csv
  python scripts/backfill_history.py --update-chart  # …and rewrite the monthly
                                                     #    chart arrays in app.js

Source: MeroLagani's chart API (dated daily bars: close + turnover), from 2020.
Rows already in index.csv are kept as they are — they come from the daily
Action and also carry breadth/transactions. Use --overwrite to replace them.

The chart arrays (allData in app.js) become real month-end closes and
average daily turnover (Rs B), so the fallback chart no longer depends on
interpolated values.
"""
import argparse, json, re, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from fetch_nepse import (INDEX_CSV, ROOT, HIST_DIR, log, merolagani_history,
                         parse_merolagani_bars, read_index_history, write_index_history,
                         monthly_from_history)

SOURCE = 'merolagani-history'
APP_JS = ROOT / 'app.js'
CHART_RE = re.compile(r'// ---- CHART DATA ----\n.*?(?=// ── Verify counts at runtime)', re.S)


def build_rows(bars):
    rows, prev = [], None
    for b in bars:
        chg = round(b['index'] - prev, 2) if prev else None
        pct = round((b['index'] - prev) / prev * 100, 2) if prev else None
        rows.append({'date': b['date'], 'index': b['index'], 'change': chg, 'changePct': pct,
                     'turnover': b['turnover'], 'source': SOURCE})
        prev = b['index']
    return rows


def chart_block(monthly, start_label):
    labels = [m['label'] for m in monthly]
    i0 = labels.index(start_label) if start_label in labels else 0
    monthly = monthly[i0:]
    labels = [m['label'] for m in monthly]
    price = [round(m['close']) for m in monthly]
    vol, last = [], None
    for m in monthly:
        last = m['turnover_b'] if m['turnover_b'] is not None else last
        vol.append(last if last is not None else 0)
    y25 = labels.index('Jan 25') if 'Jan 25' in labels else 0
    q = lambda xs: ', '.join(json.dumps(x) for x in xs)
    return (
        '// ---- CHART DATA ----\n'
        '// NEPSE MONTHLY data — generated by scripts/backfill_history.py from\n'
        '// data/history/index.csv (MeroLagani daily bars + daily GitHub Action).\n'
        '//   price  = month-end close (index points)\n'
        '//   volume = average daily turnover in Rs Billion\n'
        '// Do not edit by hand — re-run: python scripts/backfill_history.py --update-chart\n'
        '// The daily Action\'s "monthly" series updates these at runtime as well.\n'
        'const allData = {\n'
        f'  labels: [{q(labels)}],\n'
        f'  price: [{q(price)}],\n'
        f'  volume: [{q(vol)}]\n'
        '};\n\n'
        f'// Slice indices — {len(labels)}-point monthly dataset ({labels[0]} – {labels[-1]})\n'
        f'const recent2025 = {{ start: {y25}, end: {len(labels)} }};  // Jan 2025 – latest\n'
        f'const recent3m   = {{ start: {max(0, len(labels) - 6)}, end: {len(labels)} }};  // last 6 months\n\n'
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--start', default='2020-01-01', help='first date to fetch (YYYY-MM-DD)')
    ap.add_argument('--from-file', help='use a saved MeroLagani JSON response instead of the network')
    ap.add_argument('--overwrite', action='store_true', help='replace rows already in index.csv')
    ap.add_argument('--update-chart', action='store_true', help='rewrite allData in app.js')
    ap.add_argument('--chart-start', default='Jan 21', help='first month label on the chart')
    args = ap.parse_args()

    bars = (parse_merolagani_bars(json.loads(Path(args.from_file).read_text(encoding='utf-8')))
            if args.from_file else merolagani_history(start=args.start))
    if len(bars) < 100:
        log(f'ERROR: only {len(bars)} bars received — not backfilling')
        return 1
    log(f"MeroLagani: {len(bars)} daily bars, {bars[0]['date']} → {bars[-1]['date']}")

    existing = read_index_history()
    have = {r['date'] for r in existing}
    fresh = build_rows(bars)
    if args.overwrite:
        keep = {r['date'] for r in fresh}
        merged = [r for r in existing if r['date'] not in keep] + fresh
    else:
        merged = existing + [r for r in fresh if r['date'] not in have]
    HIST_DIR.mkdir(parents=True, exist_ok=True)
    rows = write_index_history(merged)
    log(f'{INDEX_CSV.relative_to(INDEX_CSV.parents[2])}: {len(rows)} rows '
        f'({len(existing)} existing, {len(rows) - len(existing)} added)')

    if args.update_chart:
        monthly = [m for m in monthly_from_history(rows) if m['close']]
        src = APP_JS.read_text(encoding='utf-8')
        if not CHART_RE.search(src):
            log('ERROR: chart data block not found in app.js')
            return 1
        block = chart_block(monthly, args.chart_start)
        APP_JS.write_text(CHART_RE.sub(lambda m: block, src, count=1), encoding='utf-8', newline='\n')
        log(f'app.js chart arrays rewritten from month-end closes ({args.chart_start} onward)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
